name: venv_
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - python=3.9.21
  - numpy=1.26.4
  - scipy=1.13.1
  - scikit-surprise=1.1.3
  - joblib=1.4.2
  - pip=25.0
  - setuptools=75.8.0
  - wheel=0.45.1
  - flask=3.1.0
  - flask-cors=3.0.10
  - flask-restful=0.3.9
  - pandas=2.2.3